name: Publish to itch.io

on:
  workflow_dispatch: 
    inputs: 
      version:
        description: 'Version for itch.io (does nothing for now)'
        required: false
        type: string

env:
  FILE_NAME: 'UnityBuildTest'
  ITCH_USER: 'iofractorg'
  ITCH_GAME: 'unitybuildtest'
  BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'auto'

jobs:
  publish:
    name: Publish to itch.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - targetPlatform: WebGL
            channel: html
          - targetPlatform: StandaloneWindows
            channel: windows
          - targetPlatform: StandaloneLinux64
            channel: linux
          - targetPlatform: StandaloneOSX
            channel: osx
    steps:
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
      - name: Download build from Cloudflare R2
        run: aws s3 cp s3://unitybuiltest/${{ env.FILE_NAME }}-${{ matrix.targetPlatform }}-${{ github.sha }}.zip ${{ env.FILE_NAME }}.zip --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      - name: Butler Push
        run: 'butler push ${{ env.FILE_NAME }}.zip ${{ env.ITCH_USER }}/${{ env.ITCH_GAME }}:${{ matrix.channel }}'